<?php
require_once('PHPUnit/Autoload.php');
require_once dirname(__FILE__) . '/../../../../examples/simple/simplebox/simplebox.php';

/**
 * Test class for SimpleBox.
 * Generated by PHPUnit on 2012-02-15 at 03:50:31.
 */
class SimpleBoxTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var SimpleBox
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new SimpleBox;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers SimpleBox::loadSimpleBox
	 * @todo Implement testLoadSimpleBox().
	 */
	public function testLoadSimpleBox() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
