<?php

require_once('PHPUnit/Autoload.php');
require_once dirname(__FILE__) . '/../../blackbox/blackbox.php';

class BlackBox2 extends BlackBox {

	public function __construct() {
		$this->work_namespace = 'default';
		parent::__construct();
	}

}

/**
 * Test class for BlackBox.
 * Generated by PHPUnit on 2012-02-15 at 04:06:32.
 */
class BlackBox2Test extends PHPUnit_Framework_TestCase {

	/**
	 * @var BlackBox
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
//		$this->object = new BlackBox;
		$this->object = new BlackBox2;
		$this->work_namespace = 'default'; //@todo remover
		$this->object->load(array(
			'dev' => array(
				'backend' => array('fititnt', 'juliopontes'),
				'frontend' => array('_danielcorrea', 'leomiranda')
			)
		));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers BlackBox::del
	 * @todo Implement testDel().
	 */
	public function testDel() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BlackBox::get
	 * @todo Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$expected = array('fititnt', 'juliopontes');
		$actual = $this->object->get('dev.backend');
		$this->assertEquals($expected, $actual);
	}

	/**
	 * @covers BlackBox::set
	 * @todo Implement testSet().
	 */
	public function testSet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BlackBox::load
	 * @todo Implement testLoad().
	 */
	public function testLoad() {
		// Remove the following lines when you implement this test.
		unset($this->configuration_default);
		$spected = array(
			'dev' => array(
				'backend' => array('fititnt', 'juliopontes'),
				'frontend' => array('_danielcorrea', 'leomiranda')
			)
		);


		
		$this->object->load($spected, 'default');
		$this->assertEquals($spected, $this->object->configuration_default);
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers BlackBox::setNamespace
	 * @todo Implement testSetNamespace().
	 */
//	public function testSetNamespace() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}

	/**
	 * @covers BlackBox::debug
	 * @todo Implement testDebug().
	 */
//	public function testDebug() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}
}

?>
